// NoteGroup.swift — Cluster / group of semantically related notes
// CoppermindCore

import Foundation
import SwiftData

/// A group of notes that have been clustered together by semantic similarity
/// or manually organized by the user.
@Model
public final class NoteGroup {

    // MARK: - Persisted Properties

    public var id: UUID

    public var name: String
    public var createdAt: Date
    public var updatedAt: Date

    /// Whether this group was auto-generated by the clustering pipeline.
    public var autoGenerated: Bool

    /// The embedding centroid for this cluster (serialized float array).
    @Attribute(.externalStorage)
    public var embeddingCentroid: Data?

    /// Notes belonging to this group.
    public var notes: [Note]

    // MARK: - Initializer

    public init(
        id: UUID = UUID(),
        name: String,
        autoGenerated: Bool = false,
        notes: [Note] = []
    ) {
        self.id = id
        self.name = name
        self.createdAt = Date.now
        self.updatedAt = Date.now
        self.autoGenerated = autoGenerated
        self.embeddingCentroid = nil
        self.notes = notes
    }

    // MARK: - Centroid Helpers

    /// Decode the centroid embedding from persisted data.
    public func centroidEmbedding() -> [Float]? {
        guard let embeddingCentroid else { return nil }
        return embeddingCentroid.withUnsafeBytes { buffer in
            guard let baseAddress = buffer.baseAddress else { return nil }
            let count = embeddingCentroid.count / MemoryLayout<Float>.size
            let pointer = baseAddress.assumingMemoryBound(to: Float.self)
            return Array(UnsafeBufferPointer(start: pointer, count: count))
        }
    }

    /// Encode a float array into persisted centroid data.
    public func setCentroidEmbedding(_ embedding: [Float]) {
        embeddingCentroid = embedding.withUnsafeBytes { Data($0) }
    }

    public func touch() {
        updatedAt = Date.now
    }
}
