// IOSConnectionsView.swift — iOS connections / clusters tab
// CoppermindIOS

import SwiftUI
import SwiftData
import CoppermindCore

/// Displays note clusters and connections on iOS.
struct IOSConnectionsView: View {

    // MARK: - State

    @Query(sort: \NoteGroup.updatedAt, order: .reverse) private var groups: [NoteGroup]
    @Query private var connections: [Connection]
    @State private var selectedGroup: NoteGroup?

    // MARK: - Body

    var body: some View {
        NavigationStack {
            List {
                // Stats header
                Section {
                    HStack(spacing: 24) {
                        VStack {
                            Text("\(groups.count)")
                                .font(.title2.monospacedDigit().bold())
                            Text("Clusters")
                                .font(.caption)
                                .foregroundStyle(.secondary)
                        }
                        VStack {
                            Text("\(connections.count)")
                                .font(.title2.monospacedDigit().bold())
                            Text("Connections")
                                .font(.caption)
                                .foregroundStyle(.secondary)
                        }
                    }
                    .frame(maxWidth: .infinity)
                    .padding()
                }

                // Clusters
                Section("Clusters") {
                    if groups.isEmpty {
                        ContentUnavailableView(
                            "No Clusters Yet",
                            systemImage: "circle.grid.3x3",
                            description: Text("Connections and clusters are discovered automatically as you add notes.")
                        )
                        .listRowBackground(Color.clear)
                    } else {
                        ForEach(groups) { group in
                            NavigationLink(value: group) {
                                IOSClusterRow(group: group)
                            }
                        }
                    }
                }

                // Recent Connections
                Section("Recent Connections") {
                    ForEach(connections.prefix(20)) { connection in
                        IOSConnectionRow(connection: connection)
                    }
                }
            }
            .navigationTitle("Connections")
            .navigationDestination(for: NoteGroup.self) { group in
                IOSClusterDetailView(group: group)
            }
            .toolbar {
                ToolbarItem(placement: .topBarTrailing) {
                    Button {
                        // TODO: Trigger connection discovery
                    } label: {
                        Image(systemName: "arrow.triangle.2.circlepath")
                    }
                    .help("Discover Connections")
                }
            }
        }
    }
}

// MARK: - Cluster Row

struct IOSClusterRow: View {
    let group: NoteGroup

    var body: some View {
        VStack(alignment: .leading, spacing: 4) {
            HStack {
                Text(group.name)
                    .font(.headline)
                Spacer()
                Text("\(group.notes.count)")
                    .font(.caption.monospacedDigit())
                    .padding(.horizontal, 8)
                    .padding(.vertical, 3)
                    .background(.quaternary)
                    .clipShape(Capsule())
            }

            HStack {
                Text(group.autoGenerated ? "auto" : "manual")
                    .font(.caption2)
                    .foregroundStyle(.tertiary)
                Spacer()
                Text(group.updatedAt, style: .relative)
                    .font(.caption2)
                    .foregroundStyle(.tertiary)
            }
        }
        .padding(.vertical, 4)
    }
}

// MARK: - Connection Row

struct IOSConnectionRow: View {
    let connection: Connection

    var body: some View {
        HStack {
            VStack(alignment: .leading, spacing: 2) {
                Text(connection.sourceNote.title.isEmpty ? "Untitled" : connection.sourceNote.title)
                    .font(.subheadline)
                    .lineLimit(1)
                HStack(spacing: 4) {
                    Image(systemName: "arrow.right")
                        .font(.caption2)
                    Text(connection.targetNote.title.isEmpty ? "Untitled" : connection.targetNote.title)
                        .font(.caption)
                        .foregroundStyle(.secondary)
                        .lineLimit(1)
                }
            }
            Spacer()
            Text("\(Int(connection.strength * 100))%")
                .font(.caption.monospacedDigit())
                .foregroundStyle(.secondary)
        }
        .padding(.vertical, 2)
    }
}

// MARK: - Cluster Detail View

struct IOSClusterDetailView: View {
    let group: NoteGroup

    var body: some View {
        List {
            Section {
                VStack(alignment: .leading, spacing: 8) {
                    HStack {
                        Label(group.autoGenerated ? "Auto-generated" : "Manual", systemImage: "sparkles")
                            .font(.caption)
                            .foregroundStyle(.secondary)
                        Spacer()
                        Text("\(group.notes.count) notes")
                            .font(.caption)
                            .foregroundStyle(.secondary)
                    }
                }
            }

            Section("Notes") {
                ForEach(group.notes) { note in
                    NavigationLink(value: note) {
                        VStack(alignment: .leading, spacing: 4) {
                            Text(note.title.isEmpty ? "Untitled" : note.title)
                                .font(.headline)
                            Text(note.body.prefix(100).description)
                                .font(.caption)
                                .foregroundStyle(.secondary)
                                .lineLimit(2)
                        }
                    }
                }
            }
        }
        .navigationTitle(group.name)
        .navigationDestination(for: Note.self) { note in
            IOSNoteDetailView(note: note)
        }
    }
}

// MARK: - Widget Views Placeholder

/// Placeholder for iOS Widget extension views.
enum CoppermindWidgets {

    /// Small widget: shows top priority note title.
    struct SmallWidgetView: View {
        let noteTitle: String
        let category: String?

        var body: some View {
            VStack(alignment: .leading) {
                Image(systemName: "brain")
                    .foregroundStyle(.blue)
                Text(noteTitle)
                    .font(.headline)
                    .lineLimit(2)
                if let category {
                    Text(category)
                        .font(.caption)
                        .foregroundStyle(.secondary)
                }
            }
            .padding()
        }
    }

    /// Medium widget: shows 3 top priority notes.
    struct MediumWidgetView: View {
        let notes: [(title: String, category: String?)]

        var body: some View {
            VStack(alignment: .leading, spacing: 4) {
                HStack {
                    Image(systemName: "brain")
                        .foregroundStyle(.blue)
                    Text("Coppermind")
                        .font(.headline)
                }
                ForEach(Array(notes.prefix(3).enumerated()), id: \.offset) { _, note in
                    HStack {
                        Text(note.title)
                            .font(.subheadline)
                            .lineLimit(1)
                        Spacer()
                        if let cat = note.category {
                            Text(cat)
                                .font(.caption2)
                                .foregroundStyle(.secondary)
                        }
                    }
                }
            }
            .padding()
        }
    }
}
